# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer1.cpu.com:
    container_name: orderer1.cpu.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/cpu.com/orderers/orderer1.cpu.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/cpu.com/orderers/orderer1.cpu.com/tls/:/var/hyperledger/orderer/tls
        - orderer1.cpu.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  orderer2.cpu.com:
    container_name: orderer2.cpu.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/cpu.com/orderers/orderer2.cpu.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/cpu.com/orderers/orderer2.cpu.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.cpu.com:/var/hyperledger/production/orderer
    ports:
      - 7250:7050
      
  orderer3.cpu.com:
    container_name: orderer.cpu.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/cpu.com/orderers/orderer3.cpu.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/cpu.com/orderers/orderer3.cpu.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.cpu.com:/var/hyperledger/production/orderer
    ports:
      - 7350:7050
    
  orderer4.cpu.com:
    container_name: orderer4.cpu.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/cpu.com/orderers/orderer4.cpu.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/cpu.com/orderers/orderer4.cpu.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.cpu.com:/var/hyperledger/production/orderer
    ports:
      - 7450:7050
      
  orderer5.cpu.com:
    container_name: orderer5.cpu.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/cpu.com/orderer5/orderer.cpu.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/cpu.com/orderer5/orderer.cpu.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.cpu.com:/var/hyperledger/production/orderer
    ports:
      - 7550:7050

  peer0.org1.huawei.com:
    container_name: peer0.org1.huawei.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.huawei.com
      - CORE_PEER_ADDRESS=peer0.org1.huawei.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.huawei.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.huawei.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.huawei.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.huawei.com/peers/peer0.org1.huawei.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.huawei.com/peers/peer0.org1.huawei.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.huawei.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.org1.huawei.com:
    container_name: peer1.org1.huawei.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.huawei.com
      - CORE_PEER_ADDRESS=peer1.org1.huawei.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.huawei.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.huawei.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.huawei.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.huawei.com/peers/peer1.org1.huawei.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.huawei.com/peers/peer1.org1.huawei.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org1.huawei.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.org2.xiaomi.com:
    container_name: peer0.org2.xiaomi.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.xiaomi.com
      - CORE_PEER_ADDRESS=peer0.org2.xiaomi.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.xiaomi.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.xiaomi.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.xiaomi.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.xiaomi.com/peers/peer0.org2.xiaomi.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.xiaomi.com/peers/peer0.org2.xiaomi.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org2.xiaomi.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.org2.xiaomi.com:
    container_name: peer1.org2.xiaomi.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.xiaomi.com
      - CORE_PEER_ADDRESS=peer1.org2.xiaomi.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.xiaomi.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.xiaomi.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.xiaomi.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.xiaomi.com/peers/peer1.org2.xiaomi.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.xiaomi.com/peers/peer1.org2.xiaomi.com/tls:/etc/hyperledger/fabric/tls
        - peer1.org2.xiaomi.com:/var/hyperledger/production
    ports:
      - 10051:10051
